In [1]:
import csv
import pandas
import numpy

In [13]:
# reading the csv file
lightcycler_df = pandas.read_csv('20221217_Cas9_AW_RK__new.csv')
lightcycler_df.head(15)

   SamplePos SampleName  Prog#  Seg#  Cycle#    Time   Temp  465-580
0         A1     Sample      1     2       1  618400  21.02     0.50
1         A1     Sample      1     2       1  619660  21.17     0.49
2         A1     Sample      1     2       1  620920  21.17     0.51
3         A1     Sample      1     2       1  622190  21.17     0.51
4         A1     Sample      1     2       1  623440  21.17     0.50
5         A1     Sample      1     2       1  624720  21.17     0.49
6         A1     Sample      1     2       1  625980  21.24     0.50
7         A1     Sample      1     2       1  627260  21.24     0.50
8         A1     Sample      1     2       1  628520  21.24     0.49
9         A1     Sample      1     2       1  629780  21.24     0.49
10        A1     Sample      1     2       1  631040  21.32     0.49
11        A1     Sample      1     2       1  632320  21.40     0.49
12        A1     Sample      1     2       1  633590  21.40     0.49
13        A1     Sample      1     2       1  634870  21.40     0.49
14        A1     Sample      1     2       1  636130  21.40     0.48

In [12]:
# creating variables that locate sample position, temperature, and fluorescence 
sample_position = lightcycler_df['SamplePos']
temp = lightcycler_df['Temp']
RFU = lightcycler_df['465-580']

# creating a list of temperature values from 25 to 95 because the software likes it in this format
temp_list =[]
for i in range(25,96):
    temp_list.append(i)

# inserting this new column into the df
lightcycler_df['Temperature'] = temp_list

lightcycler_df

ValueError: Length of values (71) does not match length of index (977664)